[package]
name = "hy"
version = "0.1.0"
authors = ["shohi <oshohi@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7.9"
actix-web = "0.7.17"

futures = "0.1.25"
clap = "2.32.0"

reqwest = "0.9.6"
xml-rs = "0.8.0"
quick-xml = "0.13.1"

serde = "1.0.84"
serde_derive = "1.0.84"

serde-xml-rs = { git = 'https://github.com/shohi/serde-xml-rs' }
