[package]
name = "hy"
version = "0.1.0"
authors = ["shohi <oshohi@gmail.com>"]
edition = "2018"

[dependencies]
actix = "^0.7"
actix-web = "^0.7"

futures = "0.1"
clap = "2.32.0"

reqwest = "0.9.1"
xml-rs = "0.8"

serde = "1.0.79"
serde_derive = "1.0.79"
serde-xml-rs = "0.2.1"
