[package]
name = "hy"
version = "0.1.0"
authors = ["shohi <oshohi@gmail.com>"]
edition = "2018"

[[bin]]
name = "hy"
path = "src/main.rs"

[dependencies]
clap = "2.33.0"
actix = "0.8.2"
actix-web = "0.7.19"
reqwest = "0.9.17"

futures = "0.1.27"
wait-timeout = "0.2.0"

serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"

log = "0.4.6"
env_logger = "0.6.1"
chrono = "0.4.6"

termion = "1.5.2"
