[package]
name = "hy"
version = "0.1.0"
authors = ["shohi <oshohi@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7.9"
actix-web = "0.7.18"
reqwest = "0.9.11"

futures = "0.1.25"
clap = "2.32.0"
wait-timeout = "0.2.0"

serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"

log = "0.4.6"
env_logger = "0.6.1"
chrono = "0.4.6"
